name: Build & Release

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
    # Allow workflow to be triggered manually.

permissions:
  contents: read

jobs:
  build:
    name: build-test (go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x', '1.23.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build
        run: make build

      - name: Run unit tests
        run: make unittest

      - name: Run linter
        run: make lint

      - name: Run go mod tidy
        run: make tidy

  create-release:
    name: semantic-release
    if: "github.ref_name == 'master' && github.event_name != 'pull_request'"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install semantic-release and dependencies
        run: |
          npm install -g semantic-release@latest
          npm install -g @semantic-release/commit-analyzer@latest
          npm install -g @semantic-release/release-notes-generator@latest
          npm install -g @semantic-release/changelog@latest
          npm install -g @semantic-release/exec@latest
          npm install -g @semantic-release/git@latest
          npm install -g @semantic-release/github@latest
          pip install bump2version

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
